import { fileURLToPath } from "node:url";
import { build } from "esbuild";

// Bundle scripts/migrate.ts (+ its imports: drizzle-orm, postgres, the schema, the seed,
// the ported seed data) into ONE self-contained CommonJS file at dist/migrate.cjs (issue #45).
//
// Why bundle: the runtime Docker image is Next's `standalone` output — it carries only the
// node_modules `next build` traced, which does NOT include the migrate path (migrations run on
// DEPLOY, not in the app server). Rather than ship a second full node_modules to the 1GB box,
// we bundle the migrate entrypoint + its deps into a single file the runtime image can run with
// plain `node dist/migrate.cjs` (no tsx, no drizzle-kit, no @/ alias resolution needed at run).
// The migrate compose one-shot uses the SAME app image and overrides the command to run this.

const root = fileURLToPath(new URL("..", import.meta.url));

await build({
  entryPoints: [`${root}/scripts/migrate.ts`],
  bundle: true,
  platform: "node",
  target: "node24",
  format: "cjs",
  outfile: `${root}/dist/migrate.cjs`,
  // Resolve the project's `@/*` alias the same way tsconfig.json does (→ repo root).
  alias: { "@": root.replace(/\/$/, "") },
  // `server-only` is a build-time guard with no runtime behavior; stub it so the bundle
  // (which transitively could touch it) runs under plain node outside Next.
  external: [],
  banner: {
    js: "// Generated by scripts/build-migrate.mjs — do not edit. Runs DB migrations + seed on deploy.",
  },
  logLevel: "info",
});

console.log("[build-migrate] wrote dist/migrate.cjs");
